Fix NoClassDefFoundError for HTTPS connections
Missing Import-Package entries in pom.xml file for
appc-iaas-adapter-bundle module prevents from successfull
communication to managed OpenStack over HTTPS

Issue-ID: APPC-1911
Signed-off-by: Marcin Wilk <m.wilk@samsung.com>
Change-Id: Ic7605532b70bce78944b405138b7212f268d4c07